improved setup.py and added vim text editor option
sadbro/pydirman pull request #15
Opened 2022-12-21 13:55 UTC by sahil-sagwekar2652

Improved setup.py so that termcolor package is imported after it is installed

Added support for vim inside pydirman besides nano

2022-12-21 15:54 UTC, sadbro requested changes
@sahil-sagwekar2652  Aisa karde ki user choose kare vim ki pydirman or edit karne ke liye wohi run. Like 2 alag alag option daalna redundant ho gya

2022-12-21 17:23 UTC, sahil-sagwekar2652 commented
ok I'll change it likewise

2022-12-27 10:24 UTC, sahil-sagwekar2652 commented
Please review my latest commit

2022-12-28 17:03 UTC, sadbro approved these changes

2022-12-28 17:03 UTC, merged